export default database = {
  tasks: [
    {
      TaskId: 0,
      TaskName: 'Trash',
      CloneFrom: 0,
      ContentAssigned: 'Adkjfla;sdf',
      ContentHandlingWork: 'asdfdfasdfas',
      Description: 'Nice',
      Mark: 0,
      TimeManagerCommented: '2020-03-10T14:19:40.941Z',
      TimeStart: '2020-03-10T14:19:40.941Z',
      Status: 0,
      StatusName: 'New',
      CreationTime: '2020-03-10T14:19:40.941Z',
      Creator: 0,
      CreatorName: 'Nice',
      Processor: 0,
      ProcesssorName: 'Nice',
      Acceptance: true,
      AcceptanceName: 'AAA',
      ConfirmationEnded: true,
      ConfirmationEndedName: 'aaa',
      ImageConfirmation: 'string',
    },
    {
      TaskId: 0,
      TaskName: 'string',
      CloneFrom: 0,
      ContentAssigned: 'string',
      ContentHandlingWork: 'string',
      Description: 'string',
      Mark: 0,
      TimeManagerCommented: '2020-03-10T14:19:40.941Z',
      TimeStart: '2020-03-10T14:19:40.941Z',
      Status: 0,
      StatusName: 'string',
      CreationTime: '2020-03-10T14:19:40.941Z',
      Creator: 0,
      CreatorName: 'string',
      Processor: 0,
      ProcesssorName: 'string',
      Acceptance: true,
      AcceptanceName: 'string',
      ConfirmationEnded: true,
      ConfirmationEndedName: 'string',
      ImageConfirmation: 'string',
    },
  ],
  users: [
    {
      Id: 0,
      Username: 'admin',
      Password: 'admin',
      RoleId: 2,
      Fullname: 'Manager',
      Address: 'string',
      Phone: 'string',
      Email: 'string',
      Qrcode: 'string',
      DoB: '2019-02-02',
      GroupId: 0,
      GroupName: 'string',
    },
    {
      Id: 0,
      Username: 'manager',
      Password: 'admin',
      RoleId: 2,
      Fullname: 'Manager',
      Address: 'string',
      Phone: 'string',
      Email: 'string',
      Qrcode: 'string',
      DoB: '2019-02-02',
      GroupId: 0,
      GroupName: 'string',
    },
  ],
};
